### ISSUE TITLE
Monitoring tool

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/mercurio#103]
Hi,

The monitoring tool isn't working

Fábio

**Comment by ronoaldo** [comment]
Yes, after a few attempts collecting data (at the expense of a small overhead associated with the data collection and push to monitoring server) I ended up removing that features to simplify server management going forward.

More info here https://github.com/ronoaldo/mercurio/issues/99

Thanks for the heads up!

**Comment by farribeiro** [comment]
Will you continue to use the tool?

**Comment by ronoaldo** [comment]
I thought about it and don't plan to re-enable the monitoring mod.
