### ISSUE TITLE
Add mod Drawers and Tubelib

### ISSUE THREAD

**Issue by ronoaldo** [ronoaldo/mercurio#12]
Drawers offers great storage capabilities but I've heard that it can cause lag for mobile devices
I have a fork of Drawers that works with techpack (requires my techpack addon tubelib_tweaks)

https://github.com/0siribix/tubelib_tweaks
https://github.com/0siribix/drawers

https://forum.minetest.net/viewtopic.php?p=400291#p400291

**Comment by 0siribix** [comment]
tubelib tweaks has a bug with vacuum and I have been too busy IRL to work on it this week. I recommend to comment out the vacuum.lua line in init.lua until I can update it

**Comment by 0siribix** [comment]
OK, finally got Vacuum working
Vacuum will collect any dropped items in a 5x5x5 grid below the block. High Perf Vacuum will collect from 11x11x11

**Comment by farribeiro** [comment]
A created a PR what add the tubelibs2 to the game.

Is a good ideia?

**Comment by ronoaldo** [comment]
I have reviewed the tubelib2 PR and based on the mod description, that it don't adds functionality by itself, we may need to implement both the tubelib + drawers.

I'm a bit confused about the tubelib mods available at ContentDB, to be honest. I have some mods that no longer are maintained as well, generating several warnings on logs so I'm afraid they will stop working next minetest release, so I would be more likely to add mods that are maintained... 

All things considered, I'm inclined to go with these:
- Pipeworks https://content.minetest.net/packages/VanessaE/pipeworks/
- Storage Drawers https://content.minetest.net/packages/LNJ/drawers/

@0siribix - do you think it is better to use your forked versions or it is wise to use the ones from ContentDB? I'm now with a beta server and a restore script that makes testing with a replica of the server data a breeze so we can test both paths and decide which one to follow.

**Comment by 0siribix** [comment]
My fork of Drawers only adds Tubelib compatibility. It will only benefit if you use both of them. My techpack fork adds a vacuum node as well as stack refill ability. Pipeworks is very cool but it is also very demanding on the server. Techpack is much more performance friendly. Tubelib is only a library and Techpack depends on it. It's a bit confusing because Techpack has a tubelib folder. You must have tubelib2 installed independently and then install Techpack. I do not have a fork of tubelib2

**Comment by ronoaldo** [comment]
It is quite clear now, thanks!

So, I'll need to update the current PR to add:
- Your techpack fork (from here: https://github.com/0siribix/techpack_0siribix)
- Your tubelib_tweaks package (from here: https://github.com/0siribix/tubelib_tweaks)
- Your Drawers fork (from here: https://github.com/0siribix/drawers_0siribix)

I'll update the branch on the beta server and have it ready for us to test. I'll keep the lower resources as of now!

In order to keep track of the Git mods I'll probably fork them (without changes) to reference my fork in the Dockerfile so I can keep my builds reproducible.

Quick question from one of your README files: do you know if a max_stack of 1024 can cause any harm? I'm not sure it may break something in the refill part.

**Comment by 0siribix** [comment]
I must apologize, I've changed the structure of my techpack fork. When I submitted this request, I had tubelib_tweaks which required Techpack. At that time my fork was only for bugfixes with PRs to the original. I have since abandoned this as it was too difficult to maintain. Now, tubelib_tweaks is deprecated and I maintain techpack_0siribix. Please don't use tubelib_tweaks

**Comment by 0siribix** [comment]
To be clear, previously my changes were applied using tubelib_tweaks with dependence on official Techpack. Now I maintain my own fork of Techpack

**Comment by ronoaldo** [comment]
Perfect thanks! I'll use the forked versions you suggested!

**Comment by ronoaldo** [comment]
Woops, commit messages closing issues too early 😳 

In other news, @0siribix kindly test on the Mercurio beta server, now public on serverlist. I've not changed any config yet, any tweaks recommended?

Thanks for the work and help with these mods!

**Comment by ronoaldo** [comment]
OK... Note to self: never commit changes too late 😓 - I pushed to master that is why the issue was closed. Keeping this open in case we need to revert anything, but initial testing on beta looked fine. It will land on main server soon ...

**Comment by 0siribix** [comment]
Tested and mostly works but I found two different bugs.
1. If you use a Techpack Autocrafter and pull the item from the middle slot just above the on/off button, it crashes the server but only if the button is green (On). I was not able to reproduce this on my own computer or on Avalon where techpack_0siribix is up-to-date
2. After crafting several items from the crafting menu, I suddenly stopped having craft ability. I can move items to the crafting grid but I am unable to pull the resultant item from the slot. This seems to only affect my account. I logged in with an alt account and was able to craft

Re: "any tweaks recommended" - The only ideas that come to mind is check for conflicting recipes with other mods and possibly add items to gravelsieve.

Tested successfully:
1. Crafted drawers
2. Crafter tubes, autocrafter, pusher, highperf pusher, teleport box
3. Used HP pusher to pull from locked chests and push into a teleport box, from destination teleport box into a drawer controller which was connected to 18 sets of drawers. Drawers were connected to the drawer controller via tubes. Everything not mentioned above worked as expected

I recommend for someone to test each techpack item at least once and confirm that something will defect after some time. I simply don't have time to test everything. The most recent bugs I fixed were items being duplicated or lost when moving from a pushing chest to itself OR another pushing chest OR drawer controller OR a container from another mod.

**Comment by ronoaldo** [comment]
Awesome!!! Thanks for that!

Interesting, bugs you found! Some considerations:

1. Beta restarted a few times yesterday, it could be a restart not related to the issue. If you can reproduce the issue on the main server I can fetch logs and check if it is an issue. I'll try to reproduce anyway but I'm not very used to techpack! I'm using the version from git master/main branch of the repo as of yesterday.
2. This is weird... It persisted after you exited/joined the game again?

Again, thanks for the tests made and for the improvements for the mods we're using!

**Comment by 0siribix** [comment]
Tested on production server. I could not reproduce the crash when removing the item in an autocrafter. I did quickly have the bug where I cannot craft from Unified Inventory craft menu. Again, only seems to affect the TEST5000 account and not 0siribix. I am also not sure how to reproduce the issue. Yesterday when test server rebooted several times - that was when I crashed it with the bug mentioned above. Usually a crash like that happens when trying to perform an operation on a nil objectref or table. I suspect maybe the timing was when the autocrafter was changing from "On" status to "Sleep". Again, I was only able to reproduce this on the test server.

**Comment by 0siribix** [comment]
I was able to crash production server today using the same method as mentioned before. Doesn't seem to be reliable :-/
Crash happened around 4:30 PM CST (-05:00)

**Comment by ronoaldo** [comment]
Hi @0siribix - just a follow up: I could reproduce the issue of the craft not being available. It seems to be related to some old items being aliased to "" empty strings, and being in the player inventory. They will appear as empty slots but in the database where actually still there and not removed. As a result, it was breaking the craft action. I could fix by removing the data directly from the database for me, and attempted to fix by converting those items to default:stone so if you can test if that fixed for you I'll be glad.

**Comment by 0siribix** [comment]
I'm happy to know this is not related to Techpack or Drawers ^_^
I still have the issue so I'll open a new issue
