### ISSUE TITLE
As flores defindas no mod backed clay estão limitadas a 99 por stack.

### ISSUE THREAD

**Issue by jgoffredo** [ronoaldo/mercurio#139]
Eu já tinha notado este problema antes e informado ao TenPlus1, que falou que se não tiver o limite no mod a stack pode ser infinita.

Acabei de testar, o TenPlus1 está errado.

Comentei a linha 35 do arquivo flowers.lua do mod backedclay mostrada abaixo:

stack_max = 99,

Testei a pilha que forma, e ela é do tamanho default do Minetest.

Esta modificação pode ser feita no Mercúrio, mas será necessária ser refeita a cada atualização do mod.

**Comment by ronoaldo** [comment]
Deve ser corrigido com o próximo update - a mesma linha não existe na versão mais recente do mod.

Obrigado pelo recorrente suporte @jgoffredo!

**Comment by jgoffredo** [comment]
Na olhada que dei nos fontes do mod semanas atrás a linha estava  comentada.

https://notabug.org/TenPlus1/bakedclay

Agora nem mais está lá mesmo.

Isso deve resolver problemas de fazenda e estoque de flores.

**Comment by jgoffredo** [comment]
Testei no servidor de teste e funcionou perfeitamente.
