### ISSUE TITLE
Update APercy mods to latest commit

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/mercurio#162]
Hi,

APercy has made a lot of improvements to the mods, especially when it comes to entity allocation, which saves on the server's RAM

Bests regards,
Fábio

**Comment by farribeiro** [comment]
Hi,

any news about this demand?

Best Regards,

**Comment by farribeiro** [comment]
No more needed

**Comment by ronoaldo** [comment]
Thanks! Fixed by #167
