### ISSUE TITLE
Problema da variavel desc2 - desc2 var problem.

### ISSUE THREAD

**Issue by jgoffredo** [ronoaldo/mercurio#17]
Copiar a solução mostrada abaixo.

Copy the fix shown below.

https://gitlab.com/VanessaE/homedecor_modpack/-/blob/master/homedecor_kitchen/init.lua#L156

**Comment by ronoaldo** [comment]
Curiosamente, nos logs do mercurio, os itens que não aparecem no craft estão com avisos de terem paleta de cores mas não terem o paramtype2 definido. Seja lá o que isso for.

**Comment by ronoaldo** [comment]
@jgoffredo com o update feito agora pouco, o unified_inventory foi atualizado. Talvez agora as receitas apareçam. Acho que vou ter que usar a versão Git do homedecor, não parece estar atualizado na ContentDB.

**Comment by ronoaldo** [comment]
O mod mudou de lugar e o bug aparentemente ainda está aberto: mt-mods/homedecor_modpack#4
