### ISSUE TITLE
Add climbing mods

### ISSUE THREAD

**Issue by ronoaldo** [ronoaldo/mercurio#20]
Add hang glider, sailboat, climbing rope and rope with hook, as i love to climb big mountains and then hang glide from them.

Suggested by player [chef trip](https://forum.minetest.net/memberlist.php?mode=viewprofile&u=29722)
https://forum.minetest.net/viewtopic.php?p=400901#p400901

**Comment by farribeiro** [comment]
Related issue #28

**Comment by farribeiro** [comment]
Added glider mod on PR #29 

Other mod need review

**Comment by farribeiro** [comment]
Resolved partially

**Comment by ronoaldo** [comment]
Remaining mods added, already live on Beta for testing! If no regressions found, will be live tomorrow.
