### ISSUE TITLE
Update mods

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/mercurio#22]
Hello, @ronoaldo 

Please can you update the @APercy trike, hydro and demosielle to latest version in the contentdb / commit?

Best reagards
Fábio

**Comment by farribeiro** [comment]
CC @APercy

**Comment by farribeiro** [comment]
And also add ju52 mod

**Comment by ronoaldo** [comment]
Hi @farribeiro thanks for the request. I'm updating them all and will have a PR ready soon so we can merge it

I could not find the ju52 mod on ContentDB. Is it only on Github as of now?

For the NSS Helicopter, I'm testing the migration from Git to Contentdb (so we can pin stable releases in Dockerfile). @APercy  do you know if I need to add aliases for that or it will "just works" after the move?

**Comment by farribeiro** [comment]
the ju52 stay in development in apercy github... but he maybe request add this mod , then the best way is wait fish the mod and upload to contentdb

Best regards
Fábio
