### ISSUE TITLE
Add mod Xtraores

### ISSUE THREAD

**Issue by livespectare** [ronoaldo/mercurio#45]
Este mod adiciona mais mineiras e de acordo com o que li, mais armaduras e ferramentas.
https://forum.minetest.net/viewtopic.php?t=12798

**Comment by ronoaldo** [comment]
![image](https://user-images.githubusercontent.com/564649/157974875-dc0d6225-10bc-446d-8380-4e7a8d1a4f25.png)

Disponível no beta para testarmos!
