### ISSUE TITLE
Dragões não estão mais surgindo nos ninhos após o update para 1.2

### ISSUE THREAD

**Issue by livespectare** [ronoaldo/mercurio#50]
Os dragões não estão aparecendo nos ninhos. Isso se aplica aos ninhos da superfície e aos subterrâneos, não tenho certeza quanto aos ninhos em ilhas flutuantes.
Nos ninhos que visitei, aparece o item draconis:spawn_node com o texto "no texture". Acredito que este item deveria estar invisível.

O teste foi realizado tanto no server normal, quanto no server Beta.
No servidor Beta, os dragões aparecem em alguns ninhos e em outros não.

**Comment by ronoaldo** [comment]
Relacionado ao bug ElCeejo/draconis#23 ; vou tentar algum workaround no nosso server, mas talvez tenhamos que esperar pela correção do desenvolvedor.

**Comment by ronoaldo** [comment]
Na verdade está relacionado ao bug ElCeejo/draconis#24.

**Comment by livespectare** [comment]
Instalei o mod no singleplayer e o draconis apresenta uma certa estranheza: os dragões não atacam mais os jogadores com tanta ferocidade e determinação de antes. Em vários momentos, os dragões fogem, pousam, somem.
Pode me orientar como lançar minhas observações no Github do próprio draconis? Vejo que teremos que esperar uma atualização do mod.

**Comment by livespectare** [comment]
Não estou conseguindo remover as flores do draconis que agora estão ou sem textura ou unknow iten.

**Comment by livespectare** [comment]
Ronoaldo, procurei por novos ninhos de dragão pelo server. Encontrei três ninhos. Dois haviam dragões e o terceiro não. Achei estranho que os três ninhos eram de dragões de gelo.
Conseguimos matar os dois dragões. Eles estão bem mais fortes, mas três jogadores matam.
Vou continuar procurando outros ninhos pra ver se está tudo certo.

**Comment by ronoaldo** [comment]
@livespectare show de bola!!! Obrigado! Eu acho que o clear objects dizimou qualquer dragão vivo no server, e agora só em ninhos novos (gerados pelo mapa, a partir de áreas não exploradas) que vão surgir. Eu acho que não termos dragões no "simple spawn" (ou seja, como mobs regulares fora de qualquer ninho) é um bug... Vou dar uma investigada e ver se consigo corrigir!

**Comment by ronoaldo** [comment]
Eu não vou conseguir evoluir com este issue, infelizmente. Por hora vamos ter que procurar os ninhos mesmo, já que o simple spawn parece não estar funcionando como esperávamos.
