### ISSUE TITLE
Mod moreore

### ISSUE THREAD

**Issue by livespectare** [ronoaldo/mercurio#52]
Relato que os itens silver hoe e mithril hoe do mod mencionado não estão com receitas para fabricá-lo.

**Comment by ronoaldo** [comment]
O mod intencionalmente não deixa eles serem craftados, aparentemente porque todos os Hoe antigos (incluindo o de diamante, mese, etc.) foram removidos:

https://github.com/minetest-mods/moreores/blob/fb2d58d8c843aa9512f37b12436a2bb5166585f4/init.lua#L226

```
		-- Hoe registration is handled above.
		-- There are no crafting recipes for hoes, as they have been
		-- deprecated from Minetest Game:
		-- https://github.com/minetest/minetest_game/commit/9c459e77a
```

**Comment by ronoaldo** [comment]
Eu acho que podemos considerar de incluir os itens novamente, mas eu confesso que não sei se é realmente útil já que eles foram removidos do game base que usamos no mercúrio.

**Comment by livespectare** [comment]
Acho ruim a durabilidade da enxada de ferro. Daí,, particularmente, queria enxadas mais duráveis. Mas se isso for alterar demais as coisas, pode-se deixar assim.

**Comment by ronoaldo** [comment]
Entendi, então seria vantajoso no caso pela durabilidade, certo? Vou pensar em como incluir isso no "mod de overrides" que já temos no Mercúrio então.

**Comment by livespectare** [comment]
Isso. Seria pela durabilidade.
