### ISSUE TITLE
Mod nether

### ISSUE THREAD

**Issue by livespectare** [ronoaldo/mercurio#53]
Relato que os itens Book of Portals, Nether Staff of Light e Nether Staff of Ethernal Light do mod mencionado não estão com receitas para fabricá-lo.

**Comment by ronoaldo** [comment]
Analisei o código do mod e esses itens são especiais e não possuem craft, são obtidos apenas por meio de dungeos do Nether, como drop dos baús.

Resposta que obtive nos fórums:

TenPlus1: [Those are special items you can only find in nether dungeon fortresses.](https://forum.minetest.net/viewtopic.php?p=408287#p408287)

Eu avaliei de pormos uma receita no Mercúrio, mas acho que é um desafio interessante obter eles pelos baús.

**Comment by livespectare** [comment]
Perfeito. Deixar como desafio é melhor.
