### ISSUE TITLE
Adicionar mod outros mundos

### ISSUE THREAD

**Issue by livespectare** [ronoaldo/mercurio#77]
https://content.minetest.net/packages/TenPlus1/other_worlds/
Boa noite. Por favor considerar a implementação deste mod.

**Comment by livespectare** [comment]
Ronoaldo, esse mod foi incluído no servidor?

**Comment by ronoaldo** [comment]
Na verdade as ilhas flutuantes (floatlands) já param em 4096, então estamos safe

https://github.com/minetest/minetest/blob/master/minetest.conf.example#L1366

**Comment by livespectare** [comment]
Ótima notícia!!! Tô fazendo um curso esta semana, mas vou testar já já.
Obrigado.
