### ISSUE TITLE
Two items with same recipe.

### ISSUE THREAD

**Issue by jgoffredo** [ronoaldo/mercurio#81]
Steel bar and Steel handle have the same recipe.

One solution is to invert one recipe. So, one will be in one diagonal and the other in another.

The another diagonal is free, has no recipes using, does not craft any item. I tested.

Now in Portuguese:

Steel bar e Steel handle tem a mesma receita.

Uma solução seria espelhar a receita de um deles, assim uma fica em uma diagonal, e a outra na outra diagonal. Testei e não tem receita com a outra diagonal.

**Comment by jgoffredo** [comment]
Steel bar is from mod HomeDecor and Steel handle is from Xtraores.

**Comment by ronoaldo** [comment]
Thanks for sharing - it was a bug introduced when we added Xtraores. I'll add a Mercurio-only recipe to fix that as you suggested. Going to have it on beta soon for testing.

**Comment by ronoaldo** [comment]
Corrigido no meu fork do xtraores:

![Screenshot_20220710_135549](https://user-images.githubusercontent.com/564649/178154376-fddc6834-5141-4e45-8c8d-1b098b6c7762.png)

![Screenshot_20220710_135544](https://user-images.githubusercontent.com/564649/178154378-8688a27c-e93f-4e06-a981-5fe081597173.png)
