### ISSUE TITLE
Crafting Guide says no usages when it does have.

### ISSUE THREAD

**Issue by jgoffredo** [ronoaldo/mercurio#82]
It happens with several items, like Clay Brick, when it really does have. Brick Block for example.

The most easy way to see that is with Brass Ingot. Search for Brass in Crafting Guide Filter, and will be listed several items made using Brass. Click in Brass Ingot and will see it's recipe. Click again and will see a "No usages" message, but any item listed with this filter uses Brass Ingot in it's recipe.

**Comment by ronoaldo** [comment]
Looks like a bug in the inventory mod. I updated it recently, going to check if there is a newer version with a fix. Could be a bug in the way the other mod register their recipes as well 🤔

**Comment by ronoaldo** [comment]
I guess the recent updates for the inventory mod fixed this. I see usage  for the items:

![Screenshot_20220710_144936](https://user-images.githubusercontent.com/564649/178156278-16264bf8-0319-48d6-9efc-2685fcebff77.png)

![Screenshot_20220710_144959](https://user-images.githubusercontent.com/564649/178156284-923f3b15-f7fa-43e2-9bc6-368b80042ead.png)

**Comment by ronoaldo** [comment]
Closing as I feel it is now fixed by upstream! Thanks @jgoffredo
