### ISSUE TITLE
Consider add PA28 airplane and steampunk blimp 

### ISSUE THREAD

**Issue by farribeiro** [ronoaldo/mercurio#86]
Please consider add the APercy mod PA28 airplane and steampunk blimp

https://content.minetest.net/packages/apercy/steampunk_blimp/
https://content.minetest.net/packages/apercy/pa28/

Best Regards,

**Comment by ronoaldo** [comment]
Great ones! I'll do my best to include in the next server update!

**Comment by ronoaldo** [comment]
Available for testing on jupiter.ronoaldo.dev.br:30000 - development server.
